spring.application.name=BetRadar

spring.datasource.url=jdbc:postgresql://localhost:5435/betradar
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.consumer.group-id=betradar-analytics-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.value.default.type=com.kau4dev.BetRadar.application.dto.RawOddDTO
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.trusted.packages=com.kau4dev.BetRadar.application.dto

security.jwt.secret=YmV0cmFkYXItc3VwZXItc2VjcmV0LWp3dC1rZXktMjAyNi0zMmI=
security.jwt.expiration-ms=86400000
security.auth.seed.enabled=true
security.auth.seed.username=admin
security.auth.seed.password=admin12345
